# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 97c769d007281469659fb32f367ffb571301bd3ea660873843b72118bb443265ec0e959782817972b3f7e26050251d8aaedcfc17ed7122b23be49751e6569e2c

test:
  secret_key_base: 2617dc927075d01150f3d53d35cb91d65b21b7b5c3c09a320f0ad1b7eb437fb166d6af3eede0fb7fd42ef415a08f89cd8b4f9601053254d8c10ba96cc078c136

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
